---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - stack.zncdata.net
  resources:
  - hivemetastores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.zncdata.net
  resources:
  - hivemetastores/finalizers
  verbs:
  - update
- apiGroups:
  - stack.zncdata.net
  resources:
  - hivemetastores/status
  verbs:
  - get
  - patch
  - update
