apiVersion: stack.zncdata.net/v1alpha1
kind: HiveMetastore
metadata:
  labels:
    app.kubernetes.io/name: hivemetastore
    app.kubernetes.io/instance: hivemetastore-sample
    app.kubernetes.io/part-of: hive-metadata-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hive-metadata-operator
  name: hivemetastore-sample
spec:
  image:
    repository: apache/hive
    tag: 4.0.0-beta-1
  postgres:
    host: postgresql.default.svc
    port: "5432"
